use_frameworks!

platform :ios, '9.0'

target 'JJJSBridge_Example' do
  pod 'JJJSBridge', :path => '../'

  target 'JJJSBridge_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
